# application-prod.yml - Configurações de produção para API Gateway

server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

# CORS - frontend de produção
gateway:
  cors:
    allowed-origins: "https://meu-frontend.com"

# Eureka Client - produção
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-prod:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

# Actuator
management:
  endpoints:
    web:
      discovery:
        enabled: true
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: ALWAYS

# Logging - produção
logging:
  level:
    root: INFO
    org.springframework.cloud: INFO
    com.infradomain.apigateway: INFO
