# application-prod.yml — Configuração de Produção
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 3000
            response-timeout: 10s

gateway:
  cors:
    allowed-origins:
      - https://app.taptrack.com
      - https://cliente.taptrack.com

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-prod:8761/eureka/}

management:
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    tags:
      environment: prod

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: WARN
    com.infradomain.apigateway: INFO