# API Gateway - application.yml
server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
# Eureka Client Configuration
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      # Permite sobrescrever via Compose
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    # Faz com que o Eureka mostre o IP e não o host.docker.internal
    prefer-ip-address: true
    # Dinâmico para evitar conflitos se subir várias instâncias
    instance-id: ${spring.application.name}:${random.value} # api-gateway:local
# Actuator
management:
  endpoints:
    web:
      discovery:
        enabled: true
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: ALWAYS
# Logging
logging:
  level:
    web: INFO
    root: INFO
    org.springframework.cloud: INFO
    com.infradomain.apigateway: DEBUG